import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import Header from '@/components/LayoutComponents/Header/Header';

import LoadingBar from '@/components/base/loading/LoadingBar';
import Footer from '@/components/LayoutComponents/footer';
import Sidebar from '@/components/LayoutComponents/Sidebar/Sidebar';
const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
			<LoadingBar />
			<Header />
			<div className="container-base">
				<div className="flex max-w-[100%] justify-between pt-4">
					<Sidebar />
					<main className="w-[calc(100%-254px)] overflow-hidden">{children}</main>
				</div>
			</div>
			<Footer />
		</div>
	);
}
