import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/components/LayoutComponents/Header/Header';
import Sidebar from '@/components/LayoutComponents/Sidebar/Sidebar';
import { ProviderComponent } from '@/components/base/provider';
const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<ProviderComponent>
					<Header />
					<div className="bg-[#f6f5fa] h-auto">
						<div className="container-base">
							<div className="flex max-w-[100%] justify-between pt-4">
								<Sidebar />
								<main className="w-[calc(100%-254px)] overflow-hidden">{children}</main>
							</div>
						</div>
					</div>
				</ProviderComponent>
			</body>
		</html>
	);
}
