import type { Metadata } from 'next';

import '../globals.css';
import Header from '@/components/LayoutComponents/Header/Header';

import SidebarCustomer from '@/components/LayoutComponents/Sidebar/SidebarCustomer';
import Footer from '@/components/LayoutComponents/footer';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<div>
			{/* <LoadingBar /> */}
			<Header />
			<div className=" min-h-[81vh] bg-[#f6f5fa]">
				<div className=" container-customer flex gap-4 pt-4">
					<SidebarCustomer />
					<div className="w-[calc(100%-254px)] overflow-hidden">
						<main className="max-h-full overflow-y-auto">{children}</main>
					</div>
				</div>
			</div>
			<Footer />
		</div>
	);
}
