import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import Header from '@/components/LayoutComponents/Header/Header';

// import LoadingBar from '@/components/base/loading/LoadingBar';
import Footer from '@/components/LayoutComponents/footer';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'tiki Cart',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
			<Header />
			<div className="container-base">
				<main className=" overflow-hidden">{children}</main>
			</div>
			<Footer />
		</div>
	);
}
